# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/Hequnjie/PodSpecs.git'

target "Example" do
    pod 'Extensions', '~> 1.0.0'
    pod 'Common', '~> 1.0.0'
end
